version: "2" # required to adjust maintainability checks
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  method-lines:
    config:
      threshold: 300
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 20
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: true
exclude_patterns:
  - "**/*.json"
  - "**/*.lock"
  - "**/*.scss"
  - "**/*.sh"
  - "**/*.test.tsx"
  - "**/node_modules/"
  - ".github/"
  - ".images/"
  - "plugins/"
  - "services/.sechub/"
  - "services/app-api/db/"
  - "services/database/"
  - "services/topics/"
  - "services/ui-auth/"
  - "services/ui-src/public/"
  - "services/ui-src/src/libs/"
  - "services/ui-src/src/utils/testing/**"
  - "services/ui-src/src/utils/types/types.ts"
  - "services/ui/"
  - "src/"
  - "tests/"
