import path from "path";

const fs = require("fs").promises;
const FORMS_DIR = path.resolve("forms");
const ROUTES_DIR = path.resolve(FORMS_DIR, "routes");

function getJsonData(indexFile: string, reportType: string) {
  const mod = require(indexFile);
  return mod[`${reportType}ReportJson`];
}

async function getDirectories(dirPath: string) {
  const items = await fs.readdir(dirPath, { withFileTypes: true });
  return items
    .filter((dir: { isDirectory: () => boolean }) => dir.isDirectory())
    .map((dir: { name: string }) => path.join(dirPath, dir.name));
}

async function writeJsonFile(outPath: string, data: any) {
  const wrapped = {
    comment: "THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
    ...data,
  };

  const json = JSON.stringify(wrapped, null, 2);
  await fs.writeFile(outPath, json + "\n", "utf8");
}

export const buildForReportType = async (reportPath: string) => {
  const reportType = path.basename(reportPath);

  const indexFile = path.join(reportPath, "index.ts");

  try {
    const routes = getJsonData(indexFile, reportType);
    const jsonPath = path.join(FORMS_DIR, `${reportType}.json`);
    await writeJsonFile(jsonPath, routes);
    console.log(`Updated ${jsonPath}`);
  } catch (error) {
    console.error(error);
  }

  const flagsPath = path.join(reportPath, "flags");

  try {
    const flagFolders = await getDirectories(flagsPath);

    for (const flagFolder of flagFolders) {
      const flagName = path.basename(flagFolder);
      const flagIndexFile = path.join(flagFolder, "index.ts");

      try {
        const flagJson = getJsonData(flagIndexFile, reportType);

        const flagOutPath = path.join(flagsPath, `${flagName}.json`);

        await writeJsonFile(flagOutPath, flagJson);

        console.log(`Updated flag: ${flagOutPath}`);
      } catch (error) {
        console.error(error);
      }
    }
  } catch {
    // No flags folder OK
  }
};

export const buildJson = async () => {
  const reportTypes = await getDirectories(ROUTES_DIR);

  if (reportTypes.length === 0) {
    console.log("No report folders found.");
    return;
  }

  for (const reportTypePath of reportTypes) {
    await buildForReportType(reportTypePath);
  }
};

/* istanbul ignore next */
if (require.main === module) {
  buildJson().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
