/* eslint-disable no-console */
import path from "path";

const fs = require("fs").promises;
const FORMS_DIR = path.resolve("forms");
const ROUTES_DIR = path.resolve(FORMS_DIR, "routes");

function getJsonData(indexFile: string) {
  const mod = require(indexFile);
  const form = mod.ReportJson;
  return form;
}

async function getRoutesFolders() {
  const items = await fs.readdir(ROUTES_DIR, { withFileTypes: true });
  return items
    .filter((dir: { isDirectory: () => boolean }) => dir.isDirectory())
    .map((dir: { name: string }) => path.join(ROUTES_DIR, dir.name));
}

async function writeJsonFile(outPath: string, data: any) {
  const comment = {
    comment: "THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
    ...data,
  };

  const json = JSON.stringify(comment, null, 2);
  await fs.writeFile(outPath, json + "\n", "utf8");
}

async function buildJson() {
  const forms = await getRoutesFolders();
  if (forms.length < 1) return;

  for (const form of forms) {
    const formName = path.basename(form);
    const indexFile = path.join(form, "index.ts");

    try {
      const routes = getJsonData(indexFile);
      const jsonPath = path.join(FORMS_DIR, `${formName}.json`);

      await writeJsonFile(jsonPath, routes);

      console.log(`Updated ${jsonPath}`);
    } catch (error) {
      console.error(error);
    }
  }
}

buildJson().catch((error) => {
  console.error(error);
  process.exit(1);
});
