import {
  checkbox,
  date,
  dateOptional,
  dynamic,
  email,
  emailOptional,
  endDate,
  nested,
  number,
  radio,
  text,
  textOptional,
  url,
} from "utils/forms/schemas";

export default {
  apoc: {
    // TODO: change to required fields after prefilled fields are functional
    "apoc-a1": textOptional(),
    "apoc-a2a": text(),
    "apoc-a2b": email(),
    "apoc-a3a": textOptional(),
    "apoc-a3b": emailOptional(),
    "apoc-a4": textOptional(),
  },
  arp: {
    // TODO: change to required fields after prefilled fields are functional
    "arp-a5a": dateOptional(),
    "arp-a5b": dateOptional(),
    "arp-a6": textOptional(),
  },
  aap: {
    "aap-1": dynamic(),
  },
  absse: {
    "absse-a8": dynamic(),
  },
  bpc: {
    "bpc-1": number(),
    "bpc-2": number(),
  },
  bedr: {
    "bedr-1": checkbox(),
    "bedr-2": nested(radio, "bedr-1", "Proprietary system(s)"),
    "bedr-1-o7-text": nested(text, "bedr-1", "Other, specify"),
  },
  bpi: {
    "bpi-1": text(),
    "bpi-2": radio(),
    "bpi-3": text(),
    "bpi-4": text(),
    "bpi-5": text(),
    "bpi-6": text(),
    "bpi-7a": radio(),
    "bpi-7b": nested(radio, "bpi-7a", "Yes"),
    "bpi-7c": nested(text, "bpi-7b", "Yes"),
    "bpi-8a": radio(),
    "bpi-8b": nested(text, "bpi-8a", "Yes"),
    "bpi-9a": radio(),
    "bpi-9b": nested(text, "bpi-9a", "Yes"),
    "bpi-10": text(),
  },
  cpc: {
    "cpc-1": text(),
    "cpc-1-sub": date(),
    "cpc-2": url(),
    "cpc-3": radio(),
    "cpc-3-o5-text": nested(text, "cpc-3", "Other, specify"),
    "cpc-4a": checkbox(),
    "cpc-4a-o5-text": nested(text, "cpc-4a", "None of the above"),
    "cpc-4b": text(),
    "cpc-5": number(),
    "cpc-6": text(),
  },
  cedr: {
    "cedr-1": checkbox(),
    "cedr-1-o7-text": nested(text, "cedr-1", "Other"),
    "cedr-2": checkbox(),
    "cedr-2-o5-text": nested(text, "cedr-2", "Other"),
    "cedr-3": text(),
    "cedr-4": text(),
    "cedr-5": text(),
    "cedr-6": text(),
  },
  casfhag: {
    "casfhag-1": text(),
    "casfhag-2": text(),
    "casfhag-3": text(),
    "casfhag-4": text(),
  },
  cna: {
    "cna-1": text(),
    "cna-2": text(),
  },
  cam: {}, // pending
  cbss: {
    "cbss-1": text(),
    "cbss-2": text(),
    "cbss-3": text(),
    "cbss-4": text(),
  },
  cpi: {
    "cpi-1": radio(),
  },
  dpc: {
    "dpc-1": number(),
    "dpc-2": number(),
    "dpc-3": number(),
  },
  dfp: {
    "dfp-1a": number(),
    "dfp-1b": radio(),
    "dfp-1b-o5-text": nested(text, "dfp-1b", "Other"),
    "dfp-2": text(),
    "dfp-3": radio(),
    "dfp-4-start": nested(date, "dfp-3", "Yes"),
    "dfp-4-end": nested(() => endDate("dfp-4-start"), "dfp-3", "Yes"),
  },
  dedr: {
    "dedr-1": text(),
    "dedr-2": number(),
    "dedr-3": number(),
  },
  dao: {
    "dao-1": number(),
    "dao-2": number(),
    "dao-3": number(),
    "dao-4": number(),
    "dao-5a": number(),
    "dao-5b": number(),
    "dao-6a": number(),
    "dao-6b": number(),
    "dao-6c": number(),
    "dao-6d": number(),
    "dao-6e": number(),
    "dao-6f": number(),
    "dao-6g": number(),
  },
  dabs: {
    "dabs-1": number(),
    "dabs-2": number(),
    "dabs-3": number(),
    "dabs-4": number(),
    "dabs-5": number(),
    "dabs-6": number(),
    "dabs-7": number(),
    "dabs-8": number(),
    "dabs-9": number(),
    "dabs-10": number(),
  },
  dsfh: {
    "dsfh-1": number(),
    "dsfh-2": number(),
    "dsfh-3": number(),
    "dsfh-4": number(),
    "dsfh-5": number(),
    "dsfh-6": number(),
  },
  dgo: {
    "dgo-1": number(),
    "dgo-2": number(),
    "dgo-3": number(),
    "dgo-4": number(),
    "dgo-5": number(),
  },
  dgbs: {
    "dgbs-1": number(),
    "dgbs-2": number(),
    "dgbs-3": number(),
    "dgbs-4": number(),
    "dgbs-5": number(),
    "dgbs-6": number(),
    "dgbs-7": number(),
    "dgbs-8": number(),
    "dgbs-9": number(),
    "dgbs-10": number(),
  },
  dgbr: {
    "dgbr-1": number(),
    "dgbr-2": number(),
    "dgbr-3": number(),
    "dgbr-4": number(),
    "dgbr-5": number(),
    "dgbr-6": number(),
    "dgbr-7": number(),
    "dgbr-8": number(),
    "dgbr-9": number(),
    "dgbr-10": number(),
    "dgbr-11": number(),
  },
  dqm: {
    "dqm-1": radio(),
    "dqm-1-o8": nested(text, "dqm-1", "Other"),
    "dqm-2": text(),
    "dqm-3": number(),
    "dqm-4": radio(),
    "dqm-5a": nested(text, "dqm-4", "Cross-program rate"),
    "dqm-6": radio(),
    "dqm-6-o5": nested(text, "dqm-6", "Other"),
    "dqm-7": radio(),
    "dqm-7b": nested(date, "dqm-7", "No"),
    "dqm-8": text(),
  },
  ds: {}, // pending
  dpi: {
    "dpi-1": number(),
    "dpi-2": number(),
    "dpi-3": number(),
    "dpi-4": number(),
    "dpi-5": number(),
    "dpi-6": radio(),
    "dpi-7a": nested(
      number,
      "dpi-6",
      "Makes referrals to the Medicaid Fraud Control Unit (MFCU) only"
    ),
    "dpi-7b": nested(
      number,
      "dpi-6",
      "Makes referrals to the State Medicaid Agency (SMA) and MFCU concurrently"
    ),
    "dpi-7c": nested(
      number,
      "dpi-6",
      "Makes some referrals to the SMA and others directly to the MFCU"
    ),
    "dpi-8": number(),
    "dpi-9": text(),
    "dpi-10": radio(),
  },
  ebssei: {
    "ebssei-1": checkbox(),
    "ebssei-1-o13-text": nested(text, "ebssei-1", "Other"),
    "ebssei-2": checkbox(),
    "ebssei-2-o7-text": nested(text, "ebssei-2", "Other"),
  },
};
