export default {
  apoc: {
    // TODO: change to required fields after prefilled fields are functional
    "apoc-a1": "textOptional",
    "apoc-a2a": "text",
    "apoc-a2b": "email",
    "apoc-a3a": "textOptional",
    "apoc-a3b": "emailOptional",
    "apoc-a4": "textOptional",
  },
  arp: {
    // TODO: change to required fields after prefilled fields are functional
    "arp-a5a": "dateOptional",
    "arp-a5b": "dateOptional",
    "arp-a6": "textOptional",
  },
  aap: {
    "aap-1": "dynamic",
  },
  absse: {
    "absse-a8": "dynamic",
  },
  bpc: {
    "bpc-1": "number",
    "bpc-2": "number",
  },
  bedr: {
    "bedr-1": "checkbox",
    "bedr-2": {
      type: "radio",
      nested: true,
      parentFieldName: "bedr-1",
      visibleOptionValue: "Proprietary system(s)",
    },
    "bedr-1-o7-text": {
      type: "text",
      nested: true,
      parentFieldName: "bedr-1",
      visibleOptionValue: "Other, specify",
    },
  },
  bpi: {
    "bpi-1": "text",
    "bpi-2": "radio",
    "bpi-3": "text",
    "bpi-4": "text",
    "bpi-5": "text",
    "bpi-6": "text",
    "bpi-7a": "radio",
    "bpi-7b": {
      type: "radio",
      nested: true,
      parentFieldName: "bpi-7a",
      visibleOptionValue: "Yes",
    },
    "bpi-7c": {
      type: "text",
      nested: true,
      parentFieldName: "bpi-7b",
      visibleOptionValue: "Yes",
    },
    "bpi-8a": "radio",
    "bpi-8b": {
      type: "text",
      nested: true,
      parentFieldName: "bpi-8a",
      visibleOptionValue: "Yes",
    },
    "bpi-9a": "radio",
    "bpi-9b": {
      type: "text",
      nested: true,
      parentFieldName: "bpi-9a",
      visibleOptionValue: "Yes",
    },
    "bpi-10": "text",
  },
  cpc: {
    "cpc-1": "text",
    "cpc-1-sub": "date",
    "cpc-2": "url",
    "cpc-3": "radio",
    "cpc-3-o5-text": {
      type: "text",
      nested: true,
      parentFieldName: "cpc-3",
      visibleOptionValue: "Other, specify",
    },
    "cpc-4a": "checkbox",
    "cpc-4a-o5-text": {
      type: "text",
      nested: true,
      parentFieldName: "cpc-4a",
      visibleOptionValue: "None of the above",
    },
    "cpc-4b": "text",
    "cpc-5": "number",
    "cpc-6": "text",
  },
  cedr: {
    "cedr-1": "checkbox",
    "cedr-1-o7-text": {
      type: "text",
      nested: true,
      parentFieldName: "cedr-1",
      visibleOptionValue: "Other",
    },
    "cedr-2": "checkbox",
    "cedr-2-o5-text": {
      type: "text",
      nested: true,
      parentFieldName: "cedr-2",
      visibleOptionValue: "Other",
    },
    "cedr-3": "text",
    "cedr-4": "text",
    "cedr-5": "text",
    "cedr-6": "text",
  },
  casfhag: {
    "casfhag-1": "text",
    "casfhag-2": "text",
    "casfhag-3": "text",
    "casfhag-4": "text",
  },
  cna: {
    "cna-1": "text",
    "cna-2": "text",
  },
  cam: {}, // pending
  cbss: {
    "cbss-1": "text",
    "cbss-2": "text",
    "cbss-3": "text",
    "cbss-4": "text",
  },
  cpi: {
    "cpi-1": "radio",
  },
  dpc: {
    "dpc-1": "number",
    "dpc-2": "number",
    "dpc-3": "number",
  },
  dfp: {
    "dfp-1a": "number",
    "dfp-1b": "radio",
    "dfp-1b-o5-text": {
      type: "text",
      nested: true,
      parentFieldName: "dfp-1b",
      visibleOptionValue: "Other",
    },
    "dfp-2": "text",
    "dfp-3": "radio",
    "dfp-4-1": {
      type: "date",
      nested: true,
      parentFieldName: "dfp-3",
      visibleOptionValue: "Yes",
    },
    "dfp-4-2": {
      type: "endDate",
      dependentFieldName: "dfp-4-1",
      nested: true,
      parentFieldName: "dfp-3",
      visibleOptionValue: "Yes",
    },
  },
  dedr: {
    "dedr-1": "text",
    "dedr-2": "number",
    "dedr-3": "number",
  },
  dao: {
    "dao-1": "number",
    "dao-2": "number",
    "dao-3": "number",
    "dao-4": "number",
    "dao-5a": "number",
    "dao-5b": "number",
    "dao-6a": "number",
    "dao-6b": "number",
    "dao-6c": "number",
    "dao-6d": "number",
    "dao-6e": "number",
    "dao-6f": "number",
    "dao-6g": "number",
  },
  dabs: {
    "dabs-1": "number",
    "dabs-2": "number",
    "dabs-3": "number",
    "dabs-4": "number",
    "dabs-5": "number",
    "dabs-6": "number",
    "dabs-7": "number",
    "dabs-8": "number",
    "dabs-9": "number",
    "dabs-10": "number",
  },
  dsfh: {
    "dsfh-1": "number",
    "dsfh-2": "number",
    "dsfh-3": "number",
    "dsfh-4": "number",
    "dsfh-5": "number",
    "dsfh-6": "number",
  },
  dgo: {
    "dgo-1": "number",
    "dgo-2": "number",
    "dgo-3": "number",
    "dgo-4": "number",
    "dgo-5": "number",
  },
  dgbs: {
    "dgbs-1": "number",
    "dgbs-2": "number",
    "dgbs-3": "number",
    "dgbs-4": "number",
    "dgbs-5": "number",
    "dgbs-6": "number",
    "dgbs-7": "number",
    "dgbs-8": "number",
    "dgbs-9": "number",
    "dgbs-10": "number",
  },
  dgbr: {
    "dgbr-1": "number",
    "dgbr-2": "number",
    "dgbr-3": "number",
    "dgbr-4": "number",
    "dgbr-5": "number",
    "dgbr-6": "number",
    "dgbr-7": "number",
    "dgbr-8": "number",
    "dgbr-9": "number",
    "dgbr-10": "number",
    "dgbr-11": "number",
  },
  dqm: {
    "dqm-1": "radio",
    "dqm-1-o8": {
      type: "text",
      nested: true,
      parentFieldName: "dqm-1",
      visibleOptionValue: "Other",
    },
    "dqm-2": "text",
    "dqm-3": "number",
    "dqm-4": "radio",
    "dqm-5a": {
      type: "text",
      nested: true,
      parentFieldName: "dqm-4",
      visibleOptionValue: "Cross-program rate",
    },
    "dqm-6": "radio",
    "dqm-6-o5": {
      type: "text",
      nested: true,
      parentFieldName: "dqm-6",
      visibleOptionValue: "Other",
    },
    "dqm-7": "radio",
    "dqm-7b-1": {
      type: "date",
      nested: true,
      parentFieldName: "dqm-7",
      visibleOptionValue: "No",
    },
    "dqm-7b-2": {
      type: "endDate",
      dependentFieldName: "dqm-7b-1",
      nested: true,
      parentFieldName: "dqm-7",
      visibleOptionValue: "No",
    },
    "dqm-8": "text",
  },
  ds: {
    "ds-1": "radio",
    "ds-1-o7": {
      type: "text",
      nested: true,
      parentFieldName: "ds-1",
      visibleOptionValue: "What type of intervention?",
    },
    "ds-2": "radio",
    "ds-2-o7": {
      type: "text",
      nested: true,
      parentFieldName: "ds-2",
      visibleOptionValue: "What was the topic of intervention?",
    },
    "ds-3": "dropdown",
    "ds-4": "text",
    "ds-5": "number",
    "ds-6": "number",
    "ds-7": "date",
    "ds-8": "date",
    "ds-9": "radio",
  },
  dpi: {
    "dpi-1": "number",
    "dpi-2": "number",
    "dpi-3": "number",
    "dpi-4": "number",
    "dpi-5": "number",
    "dpi-6": "radio",
    "dpi-7a": {
      type: "number",
      nested: true,
      parentFieldName: "dpi-6",
      visibleOptionValue:
        "Makes referrals to the Medicaid Fraud Control Unit (MFCU) only",
    },
    "dpi-7b": {
      type: "number",
      nested: true,
      parentFieldName: "dpi-6",
      visibleOptionValue:
        "Makes referrals to the State Medicaid Agency (SMA) and MFCU concurrently",
    },
    "dpi-7c": {
      type: "number",
      nested: true,
      parentFieldName: "dpi-6",
      visibleOptionValue:
        "Makes some referrals to the SMA and others directly to the MFCU",
    },
    "dpi-8": "number",
    "dpi-9": "text",
    "dpi-10": "radio",
  },
  ebssei: {
    "ebssei-1": "checkbox",
    "ebssei-1-o13-text": {
      type: "text",
      nested: true,
      parentFieldName: "ebssei-1",
      visibleOptionValue: "Other",
    },
    "ebssei-2": "checkbox",
    "ebssei-2-o7-text": {
      type: "text",
      nested: true,
      parentFieldName: "ebssei-2",
      visibleOptionValue: "Other",
    },
  },
};
