import * as schema from "./completionSchemas";

export const completionSchemaMap: any = {
  checkbox: schema.checkbox(),
  checkboxOneOptional: schema.checkboxOneOptional(),
  checkboxOptional: schema.checkboxOptional(),
  checkboxSingle: schema.checkboxSingle(),
  date: schema.date(),
  dateMonthYear: schema.dateMonthYear(),
  dateOptional: schema.dateOptional(),
  dropdown: schema.dropdown(),
  dropdownOptional: schema.dropdownOptional(),
  dynamic: schema.dynamic(),
  dynamicOptional: schema.dynamicOptional(),
  email: schema.email(),
  emailOptional: schema.emailOptional(),
  futureDate: schema.futureDate(),
  number: schema.number(),
  numberNotLessThanOne: schema.numberNotLessThanOne(),
  numberNotLessThanZero: schema.numberNotLessThanZero(),
  numberNotLessThanZeroOptional: schema.numberNotLessThanZeroOptional(),
  numberOptional: schema.numberOptional(),
  numberOrSuppressed: schema.numberOrSuppressed(),
  numberOrSuppressedOrNaNr: schema.numberOrSuppressedOrNaNr(),
  numberSuppressible: schema.numberSuppressible(),
  radio: schema.radio(),
  radioOptional: schema.radioOptional(),
  ratio: schema.ratio(),
  text: schema.text(),
  textOptional: schema.textOptional(),
  url: schema.url(),
  urlOptional: schema.urlOptional(),
  validNumber: schema.validNumber(),
  validNumberOptional: schema.validNumberOptional(),
};
