import * as yup from "yup";
import { dropdownOptional, radioOptional, textOptional } from "./schemaMap";

export const metadataValidationSchema = yup.object().shape({
  newOrExistingProgram: radioOptional(),
  existingProgramNameSelection: dropdownOptional(),
  existingProgramNameSuggestion: yup.string(),
  newProgramName: yup.string(),
  programName: yup.string(),
  reportType: yup.string(),
  locked: yup.bool(),
  status: yup.string(),
  reportingPeriodStartDate: yup.number(),
  reportingPeriodEndDate: yup.number(),
  dueDate: yup.number(),
  combinedData: yup.boolean(),
  programIsPCCM: radioOptional(),
  naaarSubmissionForThisProgram: radioOptional(),
  naaarSubmissionDateForThisProgram: yup.string(),
  naaarExpectedSubmissionDateForThisProgram: yup.string(),
  lastAlteredBy: yup.string(),
  submittedBy: yup.string(),
  submittedOnDate: yup.number(),
  submissionDates: yup.array(),
  previousRevisions: yup.array(),
  submissionCount: yup.number(),
  submissionName: yup.string(),
  completionStatus: yup.mixed(),
  copyFieldDataSourceId: yup.string(),
  planTypeIncludedInProgram: radioOptional(),
  "planTypeIncludedInProgram-otherText": textOptional(),
});
