// COPY-OVER

export const mcparFieldsToCopy = {
  root: [
    "state_encounterDataValidationEntity",
    "state_encounterDataValidationSystemHipaaCompliance",
    "state_encounterDataValidationEntity-otherText",
    "state_overpaymentStandard",
    "state_overpaymentStandardContractLanguageLocation",
    "state_overpaymentStandardDescription",
    "state_overpaymentReportingMonitoringEfforts",
    "state_beneficiaryCircumstanceChangeReconciliationEfforts",
    "state_providerTerminationReportingMonitoringEfforts",
    "state_providerTerminationReportingMonitoringMetrics",
    "state_providerTerminationReportingMonitoringMetricsDescription",
    "state_ownershipControlDisclosureWebsite",
    "state_ownershipControlDisclosureWebsiteLink",
    "state_timeframesForStandardPriorAuthorizationDecisions",
    "state_stateTimeframeForStandardPriorAuthorizationDecisions",
    "state_timeframesForExpeditedPriorAuthorizationDecisions",
    "state_stateTimeframeForExpeditedPriorAuthorizationDecisions",
    "program_contractTitle",
    "program_type",
    "program_type-otherText",
    "program_coveredSpecialBenefits",
    "program_coveredSpecialBenefits-otherText",
    "program_specialBenefitsAvailabilityVariation",
    "program_encounterDataUses",
    "program_encounterDataUses-otherText",
    "program_encounterDataSubmissionCorrectionPerformanceEvaluationCriteria",
    "program_encounterDataSubmissionCorrectionPerformanceEvaluationCriteria-otherText",
    "program_encounterDataSubmissionCorrectionPerformanceEvaluationCriteriaContractLanguageLocation",
    "program_encounterDataSubmissionQualityFinancialPenaltiesContractLanguageLocation",
    "program_encounterDataQualityIncentives",
    "program_criticalIncidentDefinition",
    "program_standardAppealTimelyResolutionDefinition",
    "program_expeditedAppealTimelyResolutionDefinition",
    "program_grievanceTimelyResolutionDefinition",
    "state_bssWebsite",
    "state_bssEntityServiceAccessibility",
    "state_bssEntityLtssProgramDataIssueAssistance",
    "state_bssEntityPerformanceEvaluationMethods",
    "plan_medicalLossRatioPercentageAggregationLevel",
    "plan_medicalLossRatioPercentageAggregationLevel-otherText",
    "plan_populationSpecificMedicalLossRatioDescription",
    "plan_medicalLossRatioReportingPeriodStartDate",
    "plan_medicalLossRatioReportingPeriodEndDate",
    "program_encounterDataSubmissionTimelinessStandardDefinition",
  ],
  accessMeasures: [
    "id",
    "accessMeasure_generalCategory",
    "accessMeasure_standardDescription",
    "accessMeasure_standardType",
    "accessMeasure_standardType-otherText",
    "accessMeasure_providerType",
    "accessMeasure_providerType-otherText",
    "accessMeasure_applicableRegion",
    "accessMeasure_applicableRegion-otherText",
    "accessMeasure_population",
    "accessMeasure_population-otherText",
    "accessMeasure_monitoringMethods",
    "accessMeasure_monitoringMethods-otherText",
    "accessMeasure_oversightMethodFrequency",
    "accessMeasure_oversightMethodFrequency-otherText",
  ],
  plans: [
    "id",
    "name",
    "plan_medicalLossRatioPercentageAggregationLevel",
    "plan_medicalLossRatioPercentageAggregationLevel-otherText",
    "plan_populationSpecificMedicalLossRatioDescription",
    "plan_medicalLossRatioReportingPeriodStartDate",
    "plan_medicalLossRatioReportingPeriodEndDate",
    "program_encounterDataSubmissionTimelinessStandardDefinition",
    "plan_programIntegrityReferralPath",
    "plan_beneficiaryCircumstanceChangeReportingFrequency",
    "plan_ilosOfferedByPlan",
  ],
  bssEntities: [
    "id",
    "name",
    "bssEntity_entityType",
    "bssEntity_entityType-otherText",
    "bssEntity_entityRole",
    "bssEntity_entityRole-otherText",
  ],
  // sanctions are never copied from year to year.
};

export const naaarFieldsToCopy = {
  root: [
    "contactName",
    "contactEmailAddress",
    "reportingScenario",
    "reportingScenario_significantChange",
    "reportingScenario-otherText",
    "stateName",
    "providerTypes",
  ],
  analysisMethods: [
    "id",
    "name",
    "isRequired",
    "analysis_applicable",
    "analysis_method_applicable_plans",
    "analysis_method_frequency",
    "analysis_method_frequency-otherText",
    "custom_analysis_method_name",
    "custom_analysis_method_description",
  ],
  plans: ["id", "name"],
  standards: [
    "id",
    // analysis methods utilized per standard type
    "standard_analysisMethodsUtilized-kIrheUXLpOwF7OEypso8Ylhs",
    "standard_analysisMethodsUtilized-SDrVTHVxFa2YKrlBYjcqavbN",
    "standard_analysisMethodsUtilized-fFSst8ncbSukHlX66fqV0udO",
    "standard_analysisMethodsUtilized-tcIQ324hNsgHwHteoDgfCh08",
    "standard_analysisMethodsUtilized-lG0CeH7LIO5iGxjpaKE8v37C",
    "standard_analysisMethodsUtilized-EuccyPRHBiaTVhF1HMHnkUcR",
    "standard_analysisMethodsUtilized-vGdzNKCsiudeNeUJZgU5qhdz",
    "standard_analysisMethodsUtilized-hdz3tEHdEBvRIIdgaovgEjaa",
    "standard_analysisMethodsUtilized-9eion8H8PNrCP0AeiikpsKbx",
    "standard_analysisMethodsUtilized-Uil8wXl6t3aBsI4W8pQZlO5P",
    // standard description per standard type
    "standard_standardDescription-kIrheUXLpOwF7OEypso8Ylhs",
    "standard_standardDescription-SDrVTHVxFa2YKrlBYjcqavbN",
    "standard_standardDescription-fFSst8ncbSukHlX66fqV0udO",
    "standard_standardDescription-tcIQ324hNsgHwHteoDgfCh08",
    "standard_standardDescription-lG0CeH7LIO5iGxjpaKE8v37C",
    "standard_standardDescription-EuccyPRHBiaTVhF1HMHnkUcR",
    "standard_standardDescription-vGdzNKCsiudeNeUJZgU5qhdz",
    "standard_standardDescription-hdz3tEHdEBvRIIdgaovgEjaa",
    "standard_standardDescription-9eion8H8PNrCP0AeiikpsKbx",
    "standard_standardDescription-Uil8wXl6t3aBsI4W8pQZlO5P",
    // core provider type details per provider type
    "standard_coreProviderType-UZK4hxPVnuYGcIgNzYFHCk",
    "standard_coreProviderType-uITThePQiXntwGGViPTD62",
    "standard_coreProviderType-9kBoKCLD1dYizieU5psnJi",
    "standard_coreProviderType-kV7553HIWXekySIFLiMXLW",
    "standard_coreProviderType-nzmRTbJeqBCoAabR4oHrrh",
    "standard_coreProviderType-cb4y58UmsRXVITpWL7l9up",
    "standard_coreProviderType-tlzAMYfH4I7iIl5pjqAm7R",
    "standard_coreProviderType-WrMpSdivds4c0XfN2RPlRd",
    "standard_coreProviderType-qbR8X0YAh8vObedJPx6QTJ",
    // non-duplicated fields
    "standard_applicableRegion",
    "standard_applicableRegion-otherText",
    "standard_coreProviderType",
    "standard_populationCoveredByStandard",
    "standard_populationCoveredByStandard-otherText",
    "standard_standardType",
    "standard_standardType-otherText",
  ],
};
