LD_LOG_FILE=logs/launchdarkly-flags.log
GREP_FLAGS="-r -n -o -w"
EXCLUSIONS="--exclude-dir=.build --exclude-dir=coverage --exclude-dir=node_modules --exclude-dir=uploads"

echo "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n" > $LD_LOG_FILE

echo "# LaunchDarkly flags in components" >> $LD_LOG_FILE
(grep $GREP_FLAGS $EXCLUSIONS "useFlags().*" ./services --include=*.tsx --exclude=*.test.tsx || echo "# N/A") >> $LD_LOG_FILE
echo "" >> $LD_LOG_FILE

echo "# LaunchDarkly flags in tests" >> $LD_LOG_FILE
(grep $GREP_FLAGS $EXCLUSIONS "mockLDFlags.set.*" ./services --include=*.test.tsx || echo "# N/A") >> $LD_LOG_FILE
