LD_LOG_FILE=launchdarkly-flags.log
echo "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n" > $LD_LOG_FILE
GREP_FLAGS="-r -n -o -w --exclude-dir=coverage --exclude-dir=node_modules --exclude-dir='.*'"
echo "# LaunchDarkly flags in components" >> $LD_LOG_FILE
(grep $GREP_FLAGS "useFlags().*" ./services --include=*.tsx --exclude=*.test.tsx || echo "# None used") >> $LD_LOG_FILE
echo "" >> $LD_LOG_FILE
echo "# LaunchDarkly flags in tests" >> $LD_LOG_FILE
(grep $GREP_FLAGS "mockLDFlags.set.*" ./services --include=*.test.tsx || echo "# None used") >> $LD_LOG_FILE
