# Refer to the README.md file in within this service directory to configure all ssm parameters required for this service.
service: uploads

frameworkVersion: "3"

plugins:
  - serverless-plugin-scripts
  - serverless-s3-local
  - serverless-stack-termination-protection
  - serverless-iam-helper
  - serverless-s3-bucket-helper

s3BucketHelper:
  loggingConfiguration:
    destinationBucketName: ${env:LOGGING_BUCKET, ssm:/configuration/${self:custom.stage}/s3/accessLogsBucket, ssm:/configuration/default/s3/accessLogsBucket}
    logFilePrefix: ${env:LOGGING_BUCKET, ssm:/configuration/${self:custom.stage}/s3/accessLogsPrefix, ssm:/configuration/default/s3/accessLogsPrefix}

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iam:
    role:
      path: ${env:IAM_PATH, ssm:/configuration/${self:custom.stage}/iam/path, ssm:/configuration/default/iam/path, "/"}
      permissionsBoundary: ${env:IAM_PERMISSIONS_BOUNDARY, ssm:/configuration/${self:custom.stage}/iam/permissionsBoundaryPolicy, ssm:/configuration/default/iam/permissionsBoundaryPolicy, ""}
      statements:
        - Sid: ScanUploads
          Effect: "Allow"
          Action:
            - s3:GetObject*
            - s3:PutObjectTagging
            - s3:PutObjectVersionTagging
          Resource:
            - !Sub arn:aws:s3:::${self:service}-${self:custom.stage}-attachments-${AWS::AccountId}/*

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  serverlessTerminationProtection:
    stages:
      - main
      - val
      - production
  scripts:
    hooks:
      # This script is run locally when running 'serverless deploy'
      package:initialize: |
        set -e
        curl -L --output lambda_layer.zip https://github.com/CMSgov/lambda-clamav-layer/releases/download/0.7/lambda_layer.zip
      deploy:finalize: |
        rm lambda_layer.zip
        serverless invoke --stage ${self:custom.stage} --function avDownloadDefinitions -t Event
  s3:
    directory: ./local_buckets
    cors: ./local_cors.xml
    buckets:
      - local-mcpar-form
      - local-mlr-form
      - local-naaar-form
      - local-uploads # This is a little silly, but I've spent enough time on it.
        # the serverless-s3-local plugin starts any bucket with a BucketName
        # the attachments bucket has no name, so we need to make one up on our own
layers:
  clamDefs:
    package:
      artifact: lambda_layer.zip
functions:
  avScan:
    handler: src/antivirus.lambdaHandleEvent
    name: ${self:service}-${self:custom.stage}-avScan
    timeout: 300 # 300 seconds = 5 minutes. Average scan is 25 seconds.
    memorySize: 3008
    layers:
      - !Ref ClamDefsLambdaLayer
    environment:
      CLAMAV_BUCKET_NAME: !Ref ClamDefsBucket
      PATH_TO_AV_DEFINITIONS: "lambda/s3-antivirus/av-definitions"
  avDownloadDefinitions:
    handler: src/download-definitions.lambdaHandleEvent
    events:
      - schedule: cron(15 1 * * ? *)
    timeout: 300 # 300 seconds = 5 minutes
    memorySize: 3072
    layers:
      - !Ref ClamDefsLambdaLayer
    environment:
      CLAMAV_BUCKET_NAME: !Ref ClamDefsBucket
      PATH_TO_AV_DEFINITIONS: "lambda/s3-antivirus/av-definitions"

resources:
  Resources:
    AttachmentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${self:service}-${self:custom.stage}-attachments-${AWS::AccountId}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        CorsConfiguration: # Set the CORS policy
          CorsRules:
            - AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
              ExposedHeaders:
                - ETag
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: s3:ObjectCreated:Put
              Function: !GetAtt AvScanLambdaFunction.Arn
      DependsOn: LambdaInvokePermission
    AVBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref ClamDefsBucket
        PolicyDocument:
          Statement:
            - Action:
                - "s3:PutObject"
              Effect: "Allow"
              Resource: !Sub ${ClamDefsBucket.Arn}/*
              Principal:
                AWS: !GetAtt IamRoleLambdaExecution.Arn
            - Action:
                - "s3:GetBucketLocation"
                - "s3:ListBucket"
              Effect: "Allow"
              Resource: !Sub ${ClamDefsBucket.Arn}
              Principal:
                AWS: !GetAtt IamRoleLambdaExecution.Arn
            - Action:
                - "s3:GetObject"
              Effect: "Allow"
              Resource: !Sub ${ClamDefsBucket.Arn}/*
              Principal:
                AWS: !GetAtt IamRoleLambdaExecution.Arn
            - Sid: "AllowSSLRequestsOnly"
              Effect: Deny
              Action: "s3:*"
              Principal: "*"
              Resource:
                - !Sub arn:aws:s3:::${ClamDefsBucket}/*
                - !Sub arn:aws:s3:::${ClamDefsBucket}
              Condition:
                Bool:
                  aws:SecureTransport: false
    AttachmentsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref AttachmentsBucket
        PolicyDocument:
          Statement:
            - Action:
                - "s3:GetObject"
              Effect: "Deny"
              Resource: !Sub ${AttachmentsBucket.Arn}/*
              Principal: "*"
              Condition:
                StringNotEquals:
                  s3:ExistingObjectTag/virusScanStatus:
                    - "CLEAN"
                  aws:PrincipalArn: !GetAtt IamRoleLambdaExecution.Arn
            - Action: "s3:PutObject"
              Effect: Deny
              Principal: "*"
              NotResource:
                - !Sub ${AttachmentsBucket.Arn}/*.jpg
                - !Sub ${AttachmentsBucket.Arn}/*.png
                - !Sub ${AttachmentsBucket.Arn}/*.gif
                - !Sub ${AttachmentsBucket.Arn}/*.jpeg
                - !Sub ${AttachmentsBucket.Arn}/*.bmp
                - !Sub ${AttachmentsBucket.Arn}/*.csv
                - !Sub ${AttachmentsBucket.Arn}/*.doc
                - !Sub ${AttachmentsBucket.Arn}/*.docx
                - !Sub ${AttachmentsBucket.Arn}/*.odp
                - !Sub ${AttachmentsBucket.Arn}/*.ods
                - !Sub ${AttachmentsBucket.Arn}/*.odt
                - !Sub ${AttachmentsBucket.Arn}/*.pdf
                - !Sub ${AttachmentsBucket.Arn}/*.ppt
                - !Sub ${AttachmentsBucket.Arn}/*.pptx
                - !Sub ${AttachmentsBucket.Arn}/*.rtf
                - !Sub ${AttachmentsBucket.Arn}/*.tif
                - !Sub ${AttachmentsBucket.Arn}/*.tiff
                - !Sub ${AttachmentsBucket.Arn}/*.txt
                - !Sub ${AttachmentsBucket.Arn}/*.xls
                - !Sub ${AttachmentsBucket.Arn}/*.xlsx
                - !Sub ${AttachmentsBucket.Arn}/*.json
            - Sid: "AllowSSLRequestsOnly"
              Effect: Deny
              Action: "s3:*"
              Principal: "*"
              Resource:
                - !Sub arn:aws:s3:::${AttachmentsBucket}/*
                - !Sub arn:aws:s3:::${AttachmentsBucket}
              Condition:
                Bool:
                  aws:SecureTransport: false
    LambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: !GetAtt AvScanLambdaFunction.Arn
        Action: lambda:InvokeFunction
        Principal: s3.amazonaws.com
        SourceAccount: !Sub ${AWS::AccountId}
        SourceArn: !Sub arn:aws:s3:::${self:service}-${self:custom.stage}-attachments-${AWS::AccountId}
    ClamDefsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub ${self:service}-${self:custom.stage}-avscan-${AWS::AccountId}
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        AccessControl: Private
  Outputs:
    AttachmentsBucketName: # Print out the name of the bucket that is created
      Value: !Ref AttachmentsBucket
    AttachmentsBucketArn:
      Value: !GetAtt AttachmentsBucket.Arn
    Region:
      Value: !Sub ${AWS::Region}
