# This file is managed by macpro-mdct-core so if you'd like to change it let's do it there
name: Checkout repository and set app and branch names

on:
  workflow_call:
    inputs:
      fetch-depth:
        required: false
        type: number
        default: 1
    outputs:
      app_name_lower:
        value: ${{ jobs.checkout-repo.outputs.app_name_lower }}
      app_name_upper:
        value: ${{ jobs.checkout-repo.outputs.app_name_upper }}
      branch_name:
        value: ${{ jobs.checkout-repo.outputs.branch_name }}

jobs:
  checkout-repo:
    name: Checkout repo
    runs-on: ubuntu-latest
    outputs:
      app_name_lower: ${{ steps.extract-app-step.outputs.app_name_lower }}
      app_name_upper: ${{ steps.extract-app-step.outputs.app_name_upper }}
      branch_name: ${{ steps.extract-branch-step.outputs.branch_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: Extract app name
        id: extract-app-step
        run: |
          repo="${GITHUB_REPOSITORY##*/}"
          app="${repo##*-}"
          echo "app_name_lower=$app" >> $GITHUB_OUTPUT
          echo "app_name_upper=${app^^}" >> $GITHUB_OUTPUT

      - name: Extract branch name
        id: extract-branch-step
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            SOURCE_BRANCH="${GITHUB_HEAD_REF}"
          else
            SOURCE_BRANCH="${GITHUB_REF##*/}"
          fi

          BRANCH_NAME="$("./.github/setBranchName.sh" "$SOURCE_BRANCH")"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
