# This file is managed by macpro-mdct-core so if you'd like to change it let's do it there
name: Create Deployment PR

on:
  workflow_dispatch:
    inputs:
      target_branch:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: ".nvmrc"
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock', 'plugins/**') }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Create a PR
        run: .github/create-pr.ts
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
          APP_NAME_UPPER: ${{ vars.APP_NAME_UPPER }}
