name: Create main to val PR

on:
  push:
    branches:
      - main
  schedule:
    - cron: "1 5 * * 1-5" # weekdays at 05:01 UTC (12:01 AM EST)
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write

jobs:
  call-create-pr:
    uses: ./.github/workflows/create-pr.yml
    with:
      head_branch: main
      base_branch: val
      pr_title: "MCR val release"
