name: gitleaks
on: [pull_request, push, workflow_dispatch]
jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run gitleaks docker
        uses: docker://zricethezav/gitleaks
        with:
          args: detect --source /github/workspace/ --no-git --verbose
