# This file is managed by macpro-mdct-core so if you'd like to change it let's do it there
name: Git Secrets

on:
  push:
  workflow_dispatch:

jobs:
  gitleaks-scan:
    name: gitleaks-scan # Keep as-is to avoid updating branch rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Run Gitleaks scan
        uses: docker://zricethezav/gitleaks@sha256:c00b6bd0aeb3071cbcb79009cb16a60dd9e0a7c60e2be9ab65d25e6bc8abbb7f # v8.30.1
        with:
          args: detect --source /github/workspace/ --no-git --verbose
