name: Post Deploy

on:
  workflow_run:
    workflows: [Deploy]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'

    #   todo
    # comment out branches so post deploy runs on all branches 
    # make step for on failure that has a conditional for failure and branches of main, val, prod
    # make step for failure for snyk branches 
    # make step for success and branch production 