name: Post Deploy

on:
  push:
    branches:
      - slack-changes
  workflow_run:
    workflows: [Deploy]
    types: [completed]

jobs:
  notify_on_failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && (github.ref_name == 'slack-changes' || github.ref_name == 'main' || github.ref_name == 'val' || github.ref_name == 'production') }}
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: ":boom: The latest MCR Build Has Failed"
          SLACK_USERNAME: ${{ github.repository }} - ${{job.status}}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    #   todo
    # comment out branches so post deploy runs on all branches 
    # make step for on failure that has a conditional for failure and branches of main, val, prod
    # make step for failure for snyk branches 
    # make step for success and branch production 