name: PR Feature Flag Leaks

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  pr-feature-flag-leaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version-file: ".nvmrc"
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock', 'plugins/**') }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Create leaks report
        run: .github/pr-feature-flag-leaks.ts
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LD_SDK_KEY_PROD: ${{ secrets.LD_SDK_KEY_PROD }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
