name: Snyk auto-merge
on:
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  snyk:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'mdct-github-service-account' }}
    steps:
      - name: Auto-approve Snyk PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge for Snyk PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
