name: Snyk Scan and Report

on:
  push:
    branches: [ snyk-scan-sambr ]
  pull_request:
   branches: [ main ]
  schedule:
    - cron:  '0 0 * * *'  # run every day at midnight

permissions:
  id-token: write

jobs:
  snyk_run:
    name: Snyk Run (for PR and push)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    

    steps:
    - name: Check out repository
      uses: actions/checkout@v2


    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install --legacy-peer-deps
      working-directory: ./

    - name: Install jq
      run: sudo apt-get install -y jq
      working-directory: ./
    
    - name: Install Snyk CLI
      run: npm install -g snyk
      working-directory: ./

    - name: Run Snyk Test
      run:  snyk test --all-projects || true
      working-directory: ./
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # check 
    

  snyk_nightly_run:  
      name: Snyk Nightly Run (for nightly cron with JIRA)
      runs-on: ubuntu-latest
      #if: github.event_name == 'schedule'
      if: github.event_name == 'push'
    
      steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./

      - name: Install nodejs dependencies
        run: npm install request-promise --legacy-peer-deps
        working-directory: ./

      - name: Install additional nodejs dependencies
        run: npm install request --save --legacy-peer-deps
        working-directory: ./

      - name: Install axios
        run:  npm install axios --save --legacy-peer-deps
        working-directory: ./

      - name: Install jq
        run: sudo apt-get install -y jq
        working-directory: ./

      - name: Install Snyk CLI
        run: npm install -g snyk
        working-directory: ./

      - name: Run Snyk test
        run:  snyk test --all-projects --json > snyk_output.txt || true
        working-directory: ./
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


      - name: Set environment variables
        run: |
          echo "PROJECT_NAME=MDCT" >> $GITHUB_ENV
          echo "JIRA_PROJECT_KEY=MDCT" >> $GITHUB_ENV
          echo "JIRA_ISSUE_TYPE=Task" >> $GITHUB_ENV
          echo "JIRA_LABELS=MCR,snyk" >> $GITHUB_ENV
          echo "JIRA_EPIC_KEY=MDCT-2280" >> $GITHUB_ENV
          echo "JIRA_TITLE_PREFIX=[MCR] - Snyk : " >> $GITHUB_ENV
          
      
      - name: Install Jira library for Node.js
        run: npm install jira-client  --legacy-peer-deps
        working-directory: ./
      
      - name: Run script to parse Snyk output
        run: node parse_snyk_output.cjs snyk_output.txt
        env:
          JIRA_BASE_URL: qmacbis.atlassian.net
          JIRA_API_TOKEN: ${{ secrets.JIRA_SERVICE_USER_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_SERVICE_USERNAME }}
        working-directory: ./

