name: Upload reports

on:
  workflow_call:
    outputs:
      result_url:
        description: "URL to see e2e test results"
        value: ${{ jobs.upload-reports.outputs.result_url }}

concurrency:
  group: ${{ github.workflow }}

jobs:
  upload-reports:
    name: Upload reports
    runs-on: ubuntu-latest
    outputs:
      result_url: ${{ steps.reporturl.outputs.results }}
    steps:
      # create a unique folder name to put playwright reports in
      - name: Get timestamp
        id: timestampid
        run: echo "timestamp=$(date --utc +%Y%m%d_%H%M%SZ)" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
      # downloads artifact created from the test job
      - name: Download reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v4
        with:
          name: playwright-html-report # download from previous job
          path: downloaded-html-report # save as this when downloaded
      - name: Push files to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./downloaded-html-report # publish downloaded dir to github pages
          destination_dir: ${{ steps.timestampid.outputs.timestamp }}
      - name: Output report URL for summary
        id: reporturl
        run: |
          ORG_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          REPORT_URL=https://${ORG_NAME}.github.io/${REPO_NAME}/${{ steps.timestampid.outputs.timestamp }}/
          echo "results=$REPORT_URL" >> $GITHUB_OUTPUT
